# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

filebeat.modules:
- module: auditd
  log:
    enabled: true
- module: elasticsearch
- module: iptables
- module: kibana
- module: logstash
- module: nginx
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true

#filebeat.inputs:
#- type: container
#  enabled: true
#  paths:
#    -/var/lib/docker/containers/*/*.log
#  stream: all # can be all, stdout or stderr

# Further indexes
setup.template.pattern: "jenkins-server"
setup.template.name: "jenkins-server-*"

# filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - /var/log/jenkins/jenkins.log
#   multiline.pattern: '^[A-Z]{1}[a-z]{2} {1,2}[0-9]{1,2}, [0-9]{4} {1,2}[0-9]{1,2}:[0-9]{2}:[0-9]{2}'
#   multiline.negate: true
#   multiline.match: after
#   index: "jenkins-server-%{+yyyy.MM.dd}"




#========================== Filebeat autodiscover ==============================
# See this URL on how to run Apache2 Filebeat module: # https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
filebeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
      # This URL alos contains instructions on multi-line logs
      hints.enabled: true

#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: changeme
  indices:
    - index: "filebeat-%{[agent.version]}-auditd-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "auditd"
    - index: "filebeat-%{[agent.version]}-elasticsearch-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "elasticsearch"
    - index: "filebeat-%{[agent.version]}-iptables-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "iptables"
    - index: "filebeat-%{[agent.version]}-kibana-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "kibana"
    - index: "filebeat-%{[agent.version]}-logstash-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "logstash"
    - index: "filebeat-%{[agent.version]}-nginx-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "nginx"
    - index: "filebeat-%{[agent.version]}-system-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "system"

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "kibana:5601"
  username: elastic
  password: changeme